export const ListData = [
    {
        id: 1,
        name: "Mantshancha Residence Residence Residence",
    hosts: {
        landlord: {
            name: "Mr Pabblo",
            role: "LandLord",
            img: "/testimonial/1.png",
            languages: ["Sepedi", "English",]
        },
        caretaker: [
            {
                name: "Mrs Kgabs",
                role: "CareTaker",
                img: "/pagePhotos/key3.jpg",
                languages: ["Sepedi", "English"],
            },
            {
                name: "Mrs Kgabs",
                role: "CareTaker",
                img: "/testimonial/2.png",
                languages: ["Sepedi", "English"],
            },
        ],
    },
        image: [
            "/singlepage/apart1.jpg",
            "/singlepage/apart2.jpg",
            "/singlepage/apart3.jpg",
            "/singlepage/apart4.jpg",
            "/singlepage/apart5.png",
        ],
        offers: {
            wifi: "Unlimited Free Wifi",
            electricity: "Free electrity",
            kitchen: "Sharing kitchen",
            laundryMachine: "Free washing machine",
            parkingLot: "Free parking on premises",
            pool: "Pool available",
            shower: "Outdoor shower",
            security: "24/7 security",
        },
        totalRooms: 10,
        availableRooms: 2,
        resType: "Bachelor",
        distance: "20 minutes",
        deposit: {
            status: "Yes",
            type: "Refundable",
            price: 900,
        },
        price: 1200,
        location: "Mamotintane gate1",
        province: "Limpopo",
        closestCampus: "University Of Limpopo",
        latitude: -23.8813,
        longitude: 29.7299,
        rating: 5,
        reviewsNumber: 112,
        description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Culpa, voluptatum natus praesentium vero magnam iure sint deserunt earum quisquam tenetur? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Culpa, voluptatum natus praesentium vero magnam iure sint deserunt earum quisquam tenetur? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Culpa, voluptatum natus praesentium vero magnam iure sint deserunt earum quisquam tenetur?",
    },
    {
        id: 2,
        name: "Kgabs Residence",
    hosts: {
        landlord: {
            name: "Mr Pabblo",
            role: "LandLord",
            img: "/testimonial/1.png",
            languages: ["Sepedi", "English",]
        },
        caretaker: [
            {
                name: "Mrs Kgabs",
                role: "CareTaker",
                img: "/pagePhotos/key3.jpg",
                languages: ["zulu", "English"],
            },
            {
                name: "Mrs Kgabs",
                role: "CareTaker",
                img: "/testimonial/2.png",
                languages: ["zulu", "English"],
            },
        ],
    },
        image: [
            "/singlepage/apart2.jpg",
            "/singlepage/apart3.jpg",
            "/singlepage/apart4.jpg",
            "/singlepage/apart1.jpg",
            "/singlepage/apart5.png",
        ],
        offers: {
            wifi: "Unlimited Free Wifi",
            electricity: "Not Included",
            kitchen: "Sharing kitchen",
            laundryMachine: "Free washing machine",
            parkingLot: "Free parking on premises",
            shower: "Outdoor shower",
            security: "24/7 security",
        },
        totalRooms: 10,
        availableRooms: 2,
        resType: "Single",
        distance: "20 minutes",
        deposit: {
            status: "Yes",
            type: "Refundable",
            price: 400,
        },
        price: 1000,
        location: "Mamotintane gate1 hospital side",
        province: "Limpopo",
        closestCampus: "University Of Limpopo",
        latitude: -23.8753,
        longitude: 29.7375,
        rating: 3,
        reviewsNumber: 12,
        description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Culpa, voluptatum natus praesentium vero magnam iure sint deserunt earum quisquam tenetur? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Culpa, voluptatum natus praesentium vero magnam iure sint deserunt earum quisquam tenetur? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Culpa, voluptatum natus praesentium vero magnam iure sint deserunt earum quisquam tenetur?",
    },
    {
        id: 3,
        name: "Pabblo Residence",
    hosts: {
        landlord: {
            name: "Mr Mantshancha",
            role: "LandLord",
            img: "/testimonial/1.png",
            languages: ["Vhen", "English",]
        },
        caretaker: [
            {
                name: "Mrs Kgabs",
                role: "CareTaker",
                img: "/pagePhotos/key3.jpg",
                languages: ["Sepedi", "English"],
            },
            {
                name: "Mrs Kgabs",
                role: "CareTaker",
                img: "/testimonial/2.png",
                languages: ["Zulu", "English"],
            },
        ],
    },
        image: [
            "/singlepage/apart3.jpg",
            "/singlepage/apart4.jpg",
            "/singlepage/apart2.jpg",
            "/singlepage/apart1.jpg",
            "/singlepage/apart5.png",
        ],
        offers: {
            wifi: "Unlimited Free Wifi",
            electricity: "Free electrity",
            kitchen: "Sharing kitchen",
            laundryMachine: "Free washing machine",
            parkingLot: "Free parking on premises",
            pool: "Pool available",
            shower: "Outdoor shower",
            security: "24/7 security",
        },
        totalRooms: 100,
        availableRooms: 10,
        resType: "Bachelor",
        distance: "10 minutes",
        deposit: {
            status: "Yes",
            type: "Refundable",
            price: 1500,
        },
        price: 4000,
        location: "Mamotintane gate1 Hospital side",
        province: "Limpopo",
        closestCampus: "University Of Limpopo",
        latitude: -23.8753,
        longitude: 29.7399,
        rating: 9,
        reviewsNumber: 312,
        description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Culpa, voluptatum natus praesentium vero magnam iure sint deserunt earum quisquam tenetur? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Culpa, voluptatum natus praesentium vero magnam iure sint deserunt earum quisquam tenetur? Lorem ipsum dolor sit amet consectetur, adipisicing elit. Culpa, voluptatum natus praesentium vero magnam iure sint deserunt earum quisquam tenetur?",
    },
];