const FeaturedListData = [
    {
        id: 1,
        image: "/pagePhotos/key3.jpg",
        name: "1 University Of Limpopo",
        properties: 179,
        type: "University",
    },
    {
        id: 1,
        image: "/pagePhotos/key2.jpg",
        name: "2 University Of Limpopo",
        properties: 179,
        type: "University",
    },
    {
        id: 1,
        image: "/pagePhotos/key1.jpg",
        name: "3 University Of Limpopo",
        properties: 179,
        type: "University",
    },
    {
        id: 1,
        image: "/pagePhotos/key3.jpg",
        name: "4 University Of Limpopo",
        properties: 179,
        type: "University",
    },
    {
        id: 1,
        image: "/pagePhotos/key2.jpg",
        name: "5 University Of Limpopo",
        properties: 179,
        type: "University",
    },
    {
        id: 1,
        image: "/pagePhotos/key1.jpg",
        name: "6 University Of Limpopo",
        properties: 179,
        type: "University",
    },
    {
        id: 1,
        image: "/pagePhotos/key3.jpg",
        name: "7 University Of Limpopo",
        properties: 179,
        type: "University",
    },
    {
        id: 1,
        image: "/pagePhotos/key2.jpg",
        name: "8 University Of Limpopo",
        properties: 179,
        type: "University",
    },
    {
        id: 1,
        image: "/pagePhotos/key1.jpg",
        name: "9 University Of Limpopo",
        properties: 179,
        type: "University",
    },
    {
        id: 1,
        image: "/pagePhotos/key1.jpg",
        name: "10 University Of Limpopo",
        properties: 179,
        type: "University",
    },
    {
        id: 1,
        image: "/pagePhotos/key1.jpg",
        name: "1 College",
        properties: 179,
        type: "College",
    },
    {
        id: 2,
        image: "/pagePhotos/key1.jpg",
        name: "2 College",
        properties: 179,
        type: "College",
    },
    {
        id: 3,
        image: "/pagePhotos/key1.jpg",
        name: "3 College",
        properties: 179,
        type: "College",
    },
    {
        id: 4,
        image: "/pagePhotos/key1.jpg",
        name: "4 College",
        properties: 179,
        type: "College",
    },
    {
        id: 5,
        image: "/pagePhotos/key1.jpg",
        name: "5 College",
        properties: 179,
        type: "College",
    },
    {
        id: 6,
        image: "/pagePhotos/key1.jpg",
        name: "6 College",
        properties: 179,
        type: "College",
    },
    {
        id: 7,
        image: "/pagePhotos/key1.jpg",
        name: "7 College",
        properties: 179,
        type: "College",
    },
]

export default FeaturedListData;